<?php

/**
 * @file
 * TODO: Enter file description here.
 */

/**
 * Implements hook_help().
 */
function msc_custom_components_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    case 'admin/help#block':
      return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href="@blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', array('@blocks' => url('admin/structure/block'))) . '</p>';

    // Help for another path in the block module
    case 'admin/structure/block':
      return '<p>' . t('This page provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions. Since not all themes implement the same regions, or display regions in the same way, blocks are positioned on a per-theme basis. Remember that your changes will not be saved until you click the <em>Save blocks</em> button at the bottom of the page.') . '</p>';
  }
}

/**
 * Implements hook_classy_paragraphs_list_options().
 */
function msc_custom_components_classy_paragraphs_list_options($options, $field, $instance) {
  $options['bg_grey'] = t('Backgrouns Grey');
  $options['bg_white'] = t('Bacckground White');
  $options['m_deactivated'] = t('Coming soon Module');
  return $options;
}

/**
 * Implements hook_classy_paragraphs_list_options_alter().
 */
function msc_custom_components_classy_paragraphs_list_options_alter(&$options) {
  $options['bg_grey'] = t('Call to action: Background Grey');
}

/**
 * Implements hook_menu().
 */
function msc_custom_components_menu() {
  $items = array();
  $items['admin/config/TODO-SECTION/msc_custom_components'] = array(
    'title' => 'Administer Marie Curie Custom Components',
    'description' => 'Configure settings for Marie Curie Custom Components.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('msc_custom_components_settings_form'),
    'access arguments' => array('administer msc_custom_components'),
    'file' => 'msc_custom_components.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function msc_custom_components_permission() {
  $permissions = array();
  $permissions['administer msc_custom_components'] = array(
    'title' => t('TODO: enter permission title'),
    'description' => t('TODO: enter permission description'),
  );

  return $permissions;
}
